### ISSUE TITLE
Question: Is File Fixed Size Compulsory?

### ISSUE THREAD

**Issue by rei-vilo** [spirilis/SLFS#2]
The code `SerFlash.open("/storage/mine.txt", FS_MODE_OPEN_CREATE(512, _FS_FILE_OPEN_FLAG_COMMIT));` creates a file with size = 512 bytes.

`FS_MODE_OPEN_CREATE` calls `_u32 _sl_GetCreateFsMode(_u32 maxSizeInBytes,_u32 accessFlags)`.

Is fixed size compulsory?

**Comment by spirilis** [comment]
Yes, the SimpleLink Filesystem API preallocates 4KB blocks (or 2x 4KB blocks with COMMIT option) as needed to contain the file.

Moreover, dynamic file sizes wouldn't be a good idea for another reason I will make evident with examples and more documentation...

The SimpleLink FS does not allow you to re-write already-written portions of a file, and moreover, writing to previously-not-yet-written-but-allocated portions of a file ERASES the already-written portions if you perform those writes after a close() and then re-open() using FS_MODE_OPEN_WRITE.

Major limitations in this filesystem, to be quite frank.  You can code around some of it intelligently but it really doesn't work like an SD card, EEPROM or generic serial Flash chip in that regard.

**Comment by rei-vilo** [comment]
Thanks! Good to know but not surprising. +1 for SD-card.
