### ISSUE TITLE
Question: Is const char* Compulsory? Let's Allow String Also!

### ISSUE THREAD

**Issue by rei-vilo** [spirilis/SLFS#3]
Whatever the debate against `String`, it is widely used with the Wiring / Arduino framework and thus Energia ([reference](http://energia.nu/reference/stringobject/)).

Very often, file names are dynamic.

```
    String myFileName = "/storage/";
    myFileName += "mine.txt";

    const char* buffer[64];
    myFileName.toCharArray((char*)buffer, myFileName.length()+1);

    SerFlash.begin();

    Serial.println("Writing some text to /storage/mine.txt-");
    // Create a file "/storage/mine.txt"

    SerFlash.open((char*)buffer, FS_MODE_OPEN_CREATE(512, _FS_FILE_OPEN_FLAG_COMMIT));
```

Let's allow `String` also!

```
    SerFlash.open(myFileName, FS_MODE_OPEN_CREATE(512, _FS_FILE_OPEN_FLAG_COMMIT));
```

**Comment by spirilis** [comment]
Ah, good call!  I'll look into this.  Probably won't be hard...

**Comment by spirilis** [comment]
How's that look?  Just added a String variant for open() and del().  Anywhere else you'd expect String to interact?

**Comment by spirilis** [comment]
@rei-vilo Check out the latest commit!  I decided to try my hand at adding String support for write() and readBytes().  Strictly speaking I probably didn't need to implement write(String) as I believe print/println supports String, but doing so should optimize the underlying operations a bit.

readBytes() support is a little more interesting.  Every time it runs, it reads data just as usual but does so into a malloc()'d character buffer, then allocates a new String object out of that.  It's a little ridiculous (tracing the flow of C++ constructor function calls) how many times the data gets "copied" but it does work, and I think this implementation is the "cleanest" overall.  As a plus, the implementation attempts to squash any potential memory leaks from a user continually using SerFlash.readBytes() (which generates new String objects each time).  The user may, at their option, run SerFlash.freeString() after every call to readBytes() to manually free the internal buffers used but regardless, subsequent runs of SerFlash.readBytes() automatically frees the internal buffers before creating new ones.

**Comment by spirilis** [comment]
Although maybe I should call it readString() instead?

**Comment by spirilis** [comment]
Anyway, after this, I am going to test the current SLFS lib against all the boards I can, then re-do the Energia pull request so Robert's master copy is up to date.

**Comment by rei-vilo** [comment]
Two alternatives:

First, use `return (String)text;` to return `char * text` as String. 

Second, try `size_t readBytes(String &stringResult, size_t maxlen = 1024);`

I'm afraid the memory allocation and then free may create holes, in case another variable is created in the meantime. Either a private buffer or a variable by reference seems the best option.

**Comment by spirilis** [comment]
The current implementation uses a private buffer (that is free'd and re-allocated as needed).  So I think we're good there.
